CSCI-GA-2820-SP24-001/shopcarts

tests/test_routes.py

Added tests which are covering exception handling, so that the overall code coverage now is 90%
```python …
```

improved code coverage by 5% up to 90%

---

service/routes.py
tests/test_routes.py

I did so many things today. Thanks to Prof and Yan. I feel like top of the world

Added List shopcarts functionality

---

service/routes.py
tests/test_routes.py

Created a useful filler for the root call.
```python
service/models/item.py                 54      5    91%   96, …
```

added useful root call

---

service/routes.py
tests/test_routes.py

With this PR, I'd like to submit the code which creates an item in the shopcart and tests for it. Here is my code coverage:
```python
service/models/__init__.py              3 …
```

added create item in the shopcart endpoint

---

service/routes.py
tests/test_routes.py

Added functionality to get single item from shopcart + tested it. Here is the coverage report
```python …
```

added functionality to get single item from shopcart

---

service/routes.py
tests/test_routes.py

Create update single item endpoint and tested it
```python
service/models/item.py                 54      5    91%   96, …
```

Update single item

---

service/routes.py
tests/test_routes.py

```python
service/common/error_handlers.py       33      3    91%   91-93
service/models/item.py                 50      1    98%   96
service/models/persistent_base.py      51      6    88% …
```

Adding list items in a shopcart

---

service/routes.py
tests/test_routes.py

```python
service/common/error_handlers.py       33      3    91%   91-93
service/models/item.py                 50      1    98%   96
service/models/persistent_base.py      51      5    90% …
```

Delete an item

---

service/models/item.py
service/routes.py
tests/test_item_model.py
tests/test_routes.py

Added three new functions on how to exctract the items from the cart based on three filters:
1) Product ID
2) Quantity
3) Product ID and the quantity
Covered the code with my newly designed test-case. Finally, I have also added modifications to my route, so that the path `get items` would be listening for the query parameters from now on.

Added filtering queries to the Item model and get items route

---

service/routes.py
tests/test_routes.py

```
service/common/error_handlers.py       33      3    91%   91-93
service/models/item.py                 66      1    98%   97
service/models/persistent_base.py      51      1    98%   41 …
```

Added ability to clear all items from shopcart

---

service/models/item.py
service/routes.py
tests/test_item_model.py
tests/test_routes.py

removed filtering by both product_id and quantity for items

del: removed filtering by both product_id and quantity for models

---

service/routes.py
tests/test_routes.py

I have improved the code coverage for our `routes.py` file. Please review for the new changes

Fixed codecov coverage by adding tests to the lines which were not covered before

---

Dockerfile
Makefile
k8s/deployment.yaml
k8s/ingress.yaml
k8s/postgresql.yaml
k8s/pv.yaml
k8s/secret.yaml
k8s/service.yaml

Please run `make setup-cluster` to set up your cluster locally. All the files needed for the set up are here

K3 cluster

---

features/environment
features/shopcarts.feature
features/steps/shopcarts_steps
features/steps/web_steps

Referenced https://github.com/nyu-devops/lab-flask-bdd
Tried my best, may need some edits

Created bdd .feature file and accompanying steps.py files

---

features/shopcarts.feature

Commented out content in feature file so we can update with our specific scenarios

Commented out content in feature file

---

service/models/shopcart.py
service/routes.py
service/static/index.html
service/static/js/rest_api.js

- create shopcart
- list all shopcarts + based on their user_id (search button)
- delete shopcart
- retrieve a shopcart
UPDATE SHOPCART IS STILL IN PROGRESS
- create an item
- delete an item
- list all items + based on the quantity, or 
UPDATE ITEM IS STILL IN PROGRESS

created functions

---

Makefile
service/models/item.py
service/routes.py
service/static/index.html
service/static/js/rest_api.js
tests/test_routes.py

Finished all the functionality for CRUD of Shopcarts and Items. Need tests

Finished User Interface implementation

---

.tekton/events/trigger_template.yaml
.tekton/pipeline.yaml
Makefile
features/shopcarts.feature
features/steps/web_steps.py
k8s/postgresql.yaml
service/static/js/rest_api.js

Fixed the pipeline creation and added a `git-clone` step.
```bash
oc login --token=<YOUR_TOKEN_GOES_HERE> --server=<YOUR_SERVER>
oc project <YOUR_OPENSHIFT_USERNAME>-dev
oc apply -f k8s/postgresql.yaml
oc apply -f .tekton/workspace.yaml
oc apply -f .tekton/pipeline.yaml
```

created `list shopcarts` BDD test + added `git clone` step to the pipeline

---

features/shopcarts.feature

- Delete an Item BD test
- Update an Item BD test
Make sure you re-initialize the container for the `behave` and `selenium` to be loaded properly:
```bash
behave
```

Adding new tests to the BDD test suite

---

README.md
features/shopcarts.feature

Added test case for listing all items in shopcart and updated README file

Added test case for listing all items in shopcart and updated README file
